use_frameworks!

platform :ios, '10.0'

abstract_target 'OSMSwiftCombined' do
    
    pod 'OSMSwift', :path => '../'
    
    target 'OSMSwift_Example' do
        #inherit! :search_paths
    end
    
    target 'OSMSwift_Tests' do
        #inherit! :search_paths
    end
    
end

